### ISSUE TITLE
JPI File note processed (received invalid data)

### ISSUE THREAD

**Issue by frankulbricht** [staski/BlueEDM#1]
Servus,
ich habe versucht mit BlueEDM ein File herunterzuladen - er scheitert mit "received invalid data".

Ich kann das File aber in EZTrends als auch in Savvy auswerten. Es ist ein EDM700 (eigentlich 800) SW-Version 293
[U230920.zip](https://github.com/staski/BlueEDM/files/12684255/U230920.zip)

als ZIP hinzugefügt, da ich .JPI nicht hochladen kann.
![IMG_1658](https://github.com/staski/BlueEDM/assets/33118666/d5a5b0c1-f2c2-43c5-b6ff-910d2638f491)

besten Dank!
Frank

**Comment by staski** [comment]
Oha, danke für die Info. Ich schaue mir das an, werde aber heute nicht mehr dazu kommen.Melde mich.Viele Grüße Carl Philipp Von meinem iPhone gesendetAm 21.09.2023 um 14:09 schrieb frankulbricht ***@***.***>:﻿
Servus,
ich habe versucht mit BlueEDM ein File herunterzuladen - er scheitert mit "received invalid data".
Ich kann das File aber in EZTrends als auch in Savvy auswerten. Es ist ein EDM700 (eigentlich 800) SW-Version 293
U230920.zip
als ZIP hinzugefügt, da ich .JPI nicht hochladen kann.

besten Dank!
Frank

**Comment by frankulbricht** [comment]
keine Hektik - finde es schonmal cool das es das überhaupt gibt :)

Wenn Du noch etwas Testdaten oder ähnliches brauchst, sag bescheid.

**Comment by staski** [comment]
seems like a "simple" checksum error. Background: the checksum calculation changed between firmware versions 299 and 300 (for single engine models). BlueEDM, so far could only deal with the new version. Thanks to the file provided, I'm able to verify checksum calculations for the old versions as well.
Turning off checksum calculation with my test tool yields:

```
Header Size: 175, Total Size: 13285

Registration: D
Download Date: 20.09.23 17:34
Model: EDM700, SW-Version: 293
Sensors: 4 cylinders, battery, oil, oat, rpm, fuelflow, cld, map [temperature unit is °F]
Fuel Flow Units: LPH, capacity1: 190, capacity2: 70, k1: 2921, k2: 2921
Alarm Thresholds: Volts Hi: 16.0, Volts Low: 12.0, Diff: 500, CHT: 450, CLD: 60, TIT: 1650, Oil High: 230, Oil Low: 75
Flights:
flight id: 2922, 23.08.23 08:52, duration: 02:05:24, fuel used:   75.9  Liters, 1255 data records
```

I will provide a new version of BlueEDM within the next few days

**Comment by staski** [comment]
> keine Hektik - finde es schonmal cool das es das überhaupt gibt :)
> 
> Wenn Du noch etwas Testdaten oder ähnliches brauchst, sag bescheid.

Hallo Frank,
vielen Dank nochmal! Ich habe den Fehler gefunden und werde ein Update zur Verfügung stellen, siehe meinen Kommentar oben.  Zu EDM700 vs. EDM800: Ich beziehe die Modellnummer direkt aus den Daten des Geräts, dort steht einfach eine 700. Es gibt wohl einen Algorithmus, wie man daraus und einigen anderen Header-Daten die "echte" Modellnummer (also 800 in Deinem Fall) ableiten kann. Den Algorithmus habe ich allerdings nicht kapiert, daher steht bei den meisten SE einfach EDM700. 
Ein anderes Problem ist mir noch aufgefallen: Bei der Ausgabe der Registrierung steht bei Deine Maschine nur ein "D" . Das liegt an meinem Parser, der nur Buchstaben, Ziffern und den Bindestrich zulässt. Bei Deiner Datei ist die Registrierung im JPI-File D_EBLW, wodurch alles nach dem Unterstrich in der Software abgeschnitten wird. Werde ich auch korrigieren!

**Comment by staski** [comment]
fixed with 1.7.1
